### ISSUE TITLE
Events are processed even if the component is hidden by other windows

### ISSUE THREAD

**Issue by topalavlad** [kristian/better-glass-pane#1]
The issue with this approach is that if another window (either same application or different application) is over the component that has the glass pane applied, the events are still processed.

Unfortunately I could not find a way to check if the window is visible or not.

**Comment by kristian** [comment]
Hello Vlad, never thought about that, so I would actually consider this a bug. Fixed with 3f5d5040c5ed14cd67ecb0bcdc84c7274ce5c34a and 0.1.4. Hope this helps. Thanks for using BetterGlassPane.

**Comment by topalavlad** [comment]
That was fast :D.
Thanks a lot.
