### ISSUE TITLE
Multiple mouse entered/exited are triggered

### ISSUE THREAD

**Issue by topalavlad** [kristian/better-glass-pane#2]
Every time you move the mouse inside a dialog and go from one component to the other, a mouse entered/exited will be generated for the whole dialog because of the mouse entered/exited event from each component.

I think these should be filtered out such that only one entered/exited is received for the whole dialog.

**Comment by kristian** [comment]
Hello Vlad, generally I see your point and I would agree that this kind of behaviour would make sense, but unfortunately that's not how the `AWTEventListener` works. In case you e.g. have a control covering the whole frame, you won't receive a `MOUSE_ENTERED/EXITED` event for the frame, but only for the button inside of that frame. The event would only trigger for the frame / dialog / window, in case the mouse enters by "touching" the frame. Also e.g. if you tab out of the window, the control in the last "entered" state would get the last `MOUSE_EXITED` event. So a) it would be very hard for me to determine, if this was really the frame exited (if even possible) and b) I don't think I could cover / document the behaviour consistently for everone to understand. I think it's easier for the applications to handle the `MOUSE_ENTERED` and `MOUSE_EXITED` events, with the knowledge that it'll trigger for each control in the root pane. I'll think a little more about this, but as far as I can tell right now, I don't see a consistent solution, sorry.

**Comment by topalavlad** [comment]
Yes, I know it's very hard to determine this. The closest I could get to it was using this method instead:
```
    private boolean shouldIgnoreEvent(Component sourceComponent, Container parent, MouseEvent event) {
        boolean otherRootPane = SwingUtilities.getRootPane(sourceComponent) != rootPane;
        boolean containedOnScreen = parent.isShowing() &&
                new Rectangle(parent.getLocationOnScreen().x, parent.getLocationOnScreen().y,
                        parent.getWidth(), parent.getHeight())
                        .contains(event.getLocationOnScreen());

        return otherRootPane && event.getID() != MouseEvent.MOUSE_EXITED
                || event.getID() == MouseEvent.MOUSE_EXITED && !otherRootPane && containedOnScreen
                || event.getID() == MouseEvent.MOUSE_ENTERED && !containedOnScreen;
    }
```
instead of 
```
if(SwingUtilities.getRootPane(sourceComponent)!=rootPane)
    return; //it's not our root pane (e.g. different window)
```
and using one more boolean flag that says if the mouse is already inside the rootContainer or not but even so I think problems can appear (on changing windows with ALT+TAB for example).

Unfortunately for a feature like grab focus on mouse over, the current behavior is unusable as it will reset the focus every time the mouse is moved over a new component. I'll try to find a more reliable solution. 

Thanks for taking a look and for the details.
